// Mocks generated by Mockito 5.4.4 from annotations
// in solution_diary_app/test/feature/user/domain/repositories/user_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:solution_diary_app/src/feature/user/data/datasources/edge_function_service.dart'
    as _i6;
import 'package:solution_diary_app/src/feature/user/data/datasources/user_api_service.dart'
    as _i3;
import 'package:solution_diary_app/src/feature/user/data/dtos/user_agreement_request_dto.dart'
    as _i5;
import 'package:solution_diary_app/src/feature/user/data/dtos/user_agreement_response_dto.dart'
    as _i2;
import 'package:supabase_flutter/supabase_flutter.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserAgreementResponseDto_0 extends _i1.SmartFake
    implements _i2.UserAgreementResponseDto {
  _FakeUserAgreementResponseDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserApiService extends _i1.Mock implements _i3.UserApiService {
  MockUserApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserAgreementResponseDto> getUserAgreementState(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserAgreementState,
          [uid],
        ),
        returnValue: _i4.Future<_i2.UserAgreementResponseDto>.value(
            _FakeUserAgreementResponseDto_0(
          this,
          Invocation.method(
            #getUserAgreementState,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.UserAgreementResponseDto>);

  @override
  _i4.Future<void> updateUserAgreementState(
    String? uid,
    _i5.UserAgreementRequestDto? dto,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserAgreementState,
          [
            uid,
            dto,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [EdgeFunctionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEdgeFunctionService extends _i1.Mock
    implements _i6.EdgeFunctionService {
  MockEdgeFunctionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> deleteUserViaEdgeFunction(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserViaEdgeFunction,
          [uid],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i7.User {
  MockUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  Map<String, dynamic> get appMetadata => (super.noSuchMethod(
        Invocation.getter(#appMetadata),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  String get aud => (super.noSuchMethod(
        Invocation.getter(#aud),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#aud),
        ),
      ) as String);

  @override
  String get createdAt => (super.noSuchMethod(
        Invocation.getter(#createdAt),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#createdAt),
        ),
      ) as String);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
      ) as bool);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
